// Main <-> agent protocol.
//
// Every connection is opened by the agent. A node therefore needs no inbound
// firewall holes beyond its own VPN ports, and works behind NAT.
//
// Two services, two trust levels:
//
//   Registration - server-authenticated TLS only, called exactly once with a
//                  one-time enrolment token, returns the agent's client
//                  certificate.
//   NodeControl  - mutual TLS with that certificate. One long-lived
//                  bidirectional stream carries everything else.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: whitenet/node/v1/node.proto

package nodepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registration_Register_FullMethodName = "/whitenet.node.v1.Registration/Register"
)

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registration turns a one-time token into a client certificate.
type RegistrationClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registrationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationClient(cc grpc.ClientConnInterface) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Registration_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
// All implementations must embed UnimplementedRegistrationServer
// for forward compatibility.
//
// Registration turns a one-time token into a client certificate.
type RegistrationServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedRegistrationServer()
}

// UnimplementedRegistrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServer struct{}

func (UnimplementedRegistrationServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistrationServer) mustEmbedUnimplementedRegistrationServer() {}
func (UnimplementedRegistrationServer) testEmbeddedByValue()                      {}

// UnsafeRegistrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServer will
// result in compilation errors.
type UnsafeRegistrationServer interface {
	mustEmbedUnimplementedRegistrationServer()
}

func RegisterRegistrationServer(s grpc.ServiceRegistrar, srv RegistrationServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registration_ServiceDesc, srv)
}

func _Registration_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registration_ServiceDesc is the grpc.ServiceDesc for Registration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitenet.node.v1.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Registration_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitenet/node/v1/node.proto",
}

const (
	NodeControl_Session_FullMethodName          = "/whitenet.node.v1.NodeControl/Session"
	NodeControl_RenewCertificate_FullMethodName = "/whitenet.node.v1.NodeControl/RenewCertificate"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeControl is everything an enrolled agent does.
type NodeControlClient interface {
	// Session is the only long-lived call. The agent opens it after connecting
	// and keeps it open; losing it is what "offline" means. Reconnects use
	// exponential backoff.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error)
	// RenewCertificate is a separate unary call because it must survive a
	// Session that cannot be established with an expiring certificate.
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[0], NodeControl_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_SessionClient = grpc.BidiStreamingClient[AgentFrame, ServerFrame]

func (c *nodeControlClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NodeControl_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
//
// NodeControl is everything an enrolled agent does.
type NodeControlServer interface {
	// Session is the only long-lived call. The agent opens it after connecting
	// and keeps it open; losing it is what "offline" means. Reconnects use
	// exponential backoff.
	Session(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error
	// RenewCertificate is a separate unary call because it must survive a
	// Session that cannot be established with an expiring certificate.
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) Session(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedNodeControlServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServer).Session(&grpc.GenericServerStream[AgentFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_SessionServer = grpc.BidiStreamingServer[AgentFrame, ServerFrame]

func _NodeControl_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitenet.node.v1.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenewCertificate",
			Handler:    _NodeControl_RenewCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _NodeControl_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "whitenet/node/v1/node.proto",
}
