// Main <-> agent protocol.
//
// Every connection is opened by the agent. A node therefore needs no inbound
// firewall holes beyond its own VPN ports, and works behind NAT.
//
// Two services, two trust levels:
//
//   Registration - server-authenticated TLS only, called exactly once with a
//                  one-time enrolment token, returns the agent's client
//                  certificate.
//   NodeControl  - mutual TLS with that certificate. One long-lived
//                  bidirectional stream carries everything else.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: whitenet/node/v1/node.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED  CommandType = 0
	CommandType_COMMAND_RESTART_CORE      CommandType = 1
	CommandType_COMMAND_UPDATE_CORE       CommandType = 2 // args: core, version ("" = latest)
	CommandType_COMMAND_UPDATE_AGENT      CommandType = 3 // args: version ("" = latest)
	CommandType_COMMAND_FETCH_LOGS        CommandType = 4 // args: core, lines
	CommandType_COMMAND_RESYNC            CommandType = 5 // discard local state and apply what follows
	CommandType_COMMAND_PROVISION_CHANNEL CommandType = 6 // OpenFlux: prepare a channel
	CommandType_COMMAND_REVOKE_CHANNEL    CommandType = 7 // OpenFlux: rotate key, drop the session
	CommandType_COMMAND_SHUTDOWN          CommandType = 8 // stop every core and exit
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_RESTART_CORE",
		2: "COMMAND_UPDATE_CORE",
		3: "COMMAND_UPDATE_AGENT",
		4: "COMMAND_FETCH_LOGS",
		5: "COMMAND_RESYNC",
		6: "COMMAND_PROVISION_CHANNEL",
		7: "COMMAND_REVOKE_CHANNEL",
		8: "COMMAND_SHUTDOWN",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":  0,
		"COMMAND_RESTART_CORE":      1,
		"COMMAND_UPDATE_CORE":       2,
		"COMMAND_UPDATE_AGENT":      3,
		"COMMAND_FETCH_LOGS":        4,
		"COMMAND_RESYNC":            5,
		"COMMAND_PROVISION_CHANNEL": 6,
		"COMMAND_REVOKE_CHANNEL":    7,
		"COMMAND_SHUTDOWN":          8,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_whitenet_node_v1_node_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_whitenet_node_v1_node_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The one-time token from the install command. Single use: Main marks it
	// spent before replying.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// A PKCS#10 certificate request. The agent generates the key pair locally
	// and never transmits the private key.
	CsrPem        []byte    `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	Host          *HostInfo `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	AgentVersion  string    `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *RegisterRequest) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeUuid string                 `protobuf:"bytes,1,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	// The signed client certificate and the CA to verify Main with.
	ClientCertPem []byte                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	CaCertPem     []byte                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *RegisterResponse) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *RegisterResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *RegisterResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        []byte                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *RenewCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentFrame_Hello
	//	*AgentFrame_Heartbeat
	//	*AgentFrame_StateApplied
	//	*AgentFrame_Metrics
	//	*AgentFrame_Traffic
	//	*AgentFrame_Event
	//	*AgentFrame_CommandResult
	//	*AgentFrame_LogChunk
	//	*AgentFrame_Channels
	Body          isAgentFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *AgentFrame) GetBody() isAgentFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentFrame) GetStateApplied() *StateApplied {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_StateApplied); ok {
			return x.StateApplied
		}
	}
	return nil
}

func (x *AgentFrame) GetMetrics() *MetricsReport {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentFrame) GetTraffic() *TrafficReport {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

func (x *AgentFrame) GetEvent() *EventReport {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentFrame) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *AgentFrame) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

func (x *AgentFrame) GetChannels() *ChannelReport {
	if x != nil {
		if x, ok := x.Body.(*AgentFrame_Channels); ok {
			return x.Channels
		}
	}
	return nil
}

type isAgentFrame_Body interface {
	isAgentFrame_Body()
}

type AgentFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentFrame_StateApplied struct {
	StateApplied *StateApplied `protobuf:"bytes,3,opt,name=state_applied,json=stateApplied,proto3,oneof"`
}

type AgentFrame_Metrics struct {
	Metrics *MetricsReport `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type AgentFrame_Traffic struct {
	Traffic *TrafficReport `protobuf:"bytes,5,opt,name=traffic,proto3,oneof"`
}

type AgentFrame_Event struct {
	Event *EventReport `protobuf:"bytes,6,opt,name=event,proto3,oneof"`
}

type AgentFrame_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,7,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type AgentFrame_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,8,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

type AgentFrame_Channels struct {
	Channels *ChannelReport `protobuf:"bytes,9,opt,name=channels,proto3,oneof"`
}

func (*AgentFrame_Hello) isAgentFrame_Body() {}

func (*AgentFrame_Heartbeat) isAgentFrame_Body() {}

func (*AgentFrame_StateApplied) isAgentFrame_Body() {}

func (*AgentFrame_Metrics) isAgentFrame_Body() {}

func (*AgentFrame_Traffic) isAgentFrame_Body() {}

func (*AgentFrame_Event) isAgentFrame_Body() {}

func (*AgentFrame_CommandResult) isAgentFrame_Body() {}

func (*AgentFrame_LogChunk) isAgentFrame_Body() {}

func (*AgentFrame_Channels) isAgentFrame_Body() {}

// Hello opens the stream. The state version it carries is what lets Main
// decide whether to resend state at all.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Host          *HostInfo              `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Cores         *CoreVersions          `protobuf:"bytes,4,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *Hello) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Hello) GetCores() *CoreVersions {
	if x != nil {
		return x.Cores
	}
	return nil
}

type HostInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os       string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch     string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Kernel   string                 `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	// Public addresses the node was able to discover. Advisory only: the
	// address clients dial is configured in the panel.
	PublicIpv4    []string `protobuf:"bytes,5,rep,name=public_ipv4,json=publicIpv4,proto3" json:"public_ipv4,omitempty"`
	PublicIpv6    []string `protobuf:"bytes,6,rep,name=public_ipv6,json=publicIpv6,proto3" json:"public_ipv6,omitempty"`
	CpuCores      uint32   `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemTotalBytes uint64   `protobuf:"varint,8,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HostInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HostInfo) GetPublicIpv4() []string {
	if x != nil {
		return x.PublicIpv4
	}
	return nil
}

func (x *HostInfo) GetPublicIpv6() []string {
	if x != nil {
		return x.PublicIpv6
	}
	return nil
}

func (x *HostInfo) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

type CoreVersions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xray          string                 `protobuf:"bytes,1,opt,name=xray,proto3" json:"xray,omitempty"`
	Wndns         string                 `protobuf:"bytes,2,opt,name=wndns,proto3" json:"wndns,omitempty"`
	Openflux      string                 `protobuf:"bytes,3,opt,name=openflux,proto3" json:"openflux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreVersions) Reset() {
	*x = CoreVersions{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreVersions) ProtoMessage() {}

func (x *CoreVersions) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreVersions.ProtoReflect.Descriptor instead.
func (*CoreVersions) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *CoreVersions) GetXray() string {
	if x != nil {
		return x.Xray
	}
	return ""
}

func (x *CoreVersions) GetWndns() string {
	if x != nil {
		return x.Wndns
	}
	return ""
}

func (x *CoreVersions) GetOpenflux() string {
	if x != nil {
		return x.Openflux
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	StateVersion  uint64                 `protobuf:"varint,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	Cores         []*CoreStatus          `protobuf:"bytes,3,rep,name=cores,proto3" json:"cores,omitempty"`
	OnlineUsers   uint32                 `protobuf:"varint,4,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Heartbeat) GetStateVersion() uint64 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *Heartbeat) GetCores() []*CoreStatus {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *Heartbeat) GetOnlineUsers() uint32 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

type CoreStatus struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Core    Core                   `protobuf:"varint,1,opt,name=core,proto3,enum=whitenet.node.v1.Core" json:"core,omitempty"`
	Running bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	// Restarts since the agent started. A climbing counter is how Main decides
	// a node is degraded rather than offline.
	RestartCount  uint32                 `protobuf:"varint,3,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStatus) Reset() {
	*x = CoreStatus{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStatus) ProtoMessage() {}

func (x *CoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStatus.ProtoReflect.Descriptor instead.
func (*CoreStatus) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *CoreStatus) GetCore() Core {
	if x != nil {
		return x.Core
	}
	return Core_CORE_UNSPECIFIED
}

func (x *CoreStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *CoreStatus) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *CoreStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CoreStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// StateApplied closes the loop on a StateUpdate. A failure is reported with
// the version that failed so Main can surface it and stop counting the node
// as converged.
type StateApplied struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Ok      bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error   string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Which cores had to be restarted to apply it, for the event log.
	Restarted     []Core `protobuf:"varint,4,rep,packed,name=restarted,proto3,enum=whitenet.node.v1.Core" json:"restarted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateApplied) Reset() {
	*x = StateApplied{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateApplied) ProtoMessage() {}

func (x *StateApplied) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateApplied.ProtoReflect.Descriptor instead.
func (*StateApplied) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *StateApplied) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StateApplied) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StateApplied) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StateApplied) GetRestarted() []Core {
	if x != nil {
		return x.Restarted
	}
	return nil
}

type MetricsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricsSample       `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsReport) GetSamples() []*MetricsSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// MetricsSample is one point in time. Counters are absolute since boot;
// Main turns them into rates. Sending absolutes means a lost report shows up
// as a gap rather than as a permanently wrong total.
type MetricsSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	At             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	CpuPercent     float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	Load1          float64                `protobuf:"fixed64,3,opt,name=load1,proto3" json:"load1,omitempty"`
	MemUsedBytes   uint64                 `protobuf:"varint,4,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes  uint64                 `protobuf:"varint,5,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,6,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,7,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	NetRxBytes     uint64                 `protobuf:"varint,8,opt,name=net_rx_bytes,json=netRxBytes,proto3" json:"net_rx_bytes,omitempty"`
	NetTxBytes     uint64                 `protobuf:"varint,9,opt,name=net_tx_bytes,json=netTxBytes,proto3" json:"net_tx_bytes,omitempty"`
	UptimeSeconds  uint64                 `protobuf:"varint,10,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	OnlineUsers    uint32                 `protobuf:"varint,11,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	TcpConnections uint32                 `protobuf:"varint,12,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsSample) Reset() {
	*x = MetricsSample{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSample) ProtoMessage() {}

func (x *MetricsSample) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSample.ProtoReflect.Descriptor instead.
func (*MetricsSample) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsSample) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *MetricsSample) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsSample) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *MetricsSample) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *MetricsSample) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *MetricsSample) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *MetricsSample) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *MetricsSample) GetNetRxBytes() uint64 {
	if x != nil {
		return x.NetRxBytes
	}
	return 0
}

func (x *MetricsSample) GetNetTxBytes() uint64 {
	if x != nil {
		return x.NetTxBytes
	}
	return 0
}

func (x *MetricsSample) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *MetricsSample) GetOnlineUsers() uint32 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

func (x *MetricsSample) GetTcpConnections() uint32 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

// TrafficReport ships deltas read from Xray's StatsService.
//
// Deltas, not totals, because Xray's own counters reset whenever it restarts.
// batch_id makes the report idempotent: Main records it and ignores a replay,
// which is what makes "retry after a dropped connection" safe.
type TrafficReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Deltas        []*TrafficDelta        `protobuf:"bytes,3,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *TrafficReport) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *TrafficReport) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *TrafficReport) GetDeltas() []*TrafficDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type TrafficDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	UplinkBytes   uint64                 `protobuf:"varint,3,opt,name=uplink_bytes,json=uplinkBytes,proto3" json:"uplink_bytes,omitempty"`
	DownlinkBytes uint64                 `protobuf:"varint,4,opt,name=downlink_bytes,json=downlinkBytes,proto3" json:"downlink_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficDelta) Reset() {
	*x = TrafficDelta{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficDelta) ProtoMessage() {}

func (x *TrafficDelta) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficDelta.ProtoReflect.Descriptor instead.
func (*TrafficDelta) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *TrafficDelta) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrafficDelta) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *TrafficDelta) GetUplinkBytes() uint64 {
	if x != nil {
		return x.UplinkBytes
	}
	return 0
}

func (x *TrafficDelta) GetDownlinkBytes() uint64 {
	if x != nil {
		return x.DownlinkBytes
	}
	return 0
}

// ChannelReport says which OpenFlux channels currently carry a session, so
// the panel can show real occupancy and Main can expire a stale lease.
type ChannelReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Channels      []*ChannelStatus       `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelReport) Reset() {
	*x = ChannelReport{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelReport) ProtoMessage() {}

func (x *ChannelReport) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelReport.ProtoReflect.Descriptor instead.
func (*ChannelReport) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *ChannelReport) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ChannelReport) GetChannels() []*ChannelStatus {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     uint64                 `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SessionActive bool                   `protobuf:"varint,2,opt,name=session_active,json=sessionActive,proto3" json:"session_active,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatus) Reset() {
	*x = ChannelStatus{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatus) ProtoMessage() {}

func (x *ChannelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatus.ProtoReflect.Descriptor instead.
func (*ChannelStatus) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *ChannelStatus) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *ChannelStatus) GetSessionActive() bool {
	if x != nil {
		return x.SessionActive
	}
	return false
}

func (x *ChannelStatus) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ChannelStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *EventReport) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	At    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	// Severity: info, warning, error.
	Severity string `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	// Type is a stable machine-readable key, e.g. core_crashed,
	// core_restarted, state_apply_failed, channel_session_started.
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Core          Core   `protobuf:"varint,5,opt,name=core,proto3,enum=whitenet.node.v1.Core" json:"core,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *Event) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetCore() Core {
	if x != nil {
		return x.Core
	}
	return Core_CORE_UNSPECIFIED
}

// LogChunk answers a COMMAND_FETCH_LOGS. Logs are pulled on demand rather
// than streamed continuously: nodes are remote and logs are large.
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Core          Core                   `protobuf:"varint,2,opt,name=core,proto3,enum=whitenet.node.v1.Core" json:"core,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Last          bool                   `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *LogChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogChunk) GetCore() Core {
	if x != nil {
		return x.Core
	}
	return Core_CORE_UNSPECIFIED
}

func (x *LogChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok        bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Free-form output, e.g. the version a core was updated to.
	Data          map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_HelloAck
	//	*ServerFrame_StateUpdate
	//	*ServerFrame_UserDelta
	//	*ServerFrame_Command
	//	*ServerFrame_HeartbeatAck
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerFrame) GetStateUpdate() *StateUpdate {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_StateUpdate); ok {
			return x.StateUpdate
		}
	}
	return nil
}

func (x *ServerFrame) GetUserDelta() *UserDelta {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_UserDelta); ok {
			return x.UserDelta
		}
	}
	return nil
}

func (x *ServerFrame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerFrame) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerFrame_StateUpdate struct {
	StateUpdate *StateUpdate `protobuf:"bytes,2,opt,name=state_update,json=stateUpdate,proto3,oneof"`
}

type ServerFrame_UserDelta struct {
	UserDelta *UserDelta `protobuf:"bytes,3,opt,name=user_delta,json=userDelta,proto3,oneof"`
}

type ServerFrame_Command struct {
	Command *Command `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type ServerFrame_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,5,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*ServerFrame_HelloAck) isServerFrame_Body() {}

func (*ServerFrame_StateUpdate) isServerFrame_Body() {}

func (*ServerFrame_UserDelta) isServerFrame_Body() {}

func (*ServerFrame_Command) isServerFrame_Body() {}

func (*ServerFrame_HeartbeatAck) isServerFrame_Body() {}

type HelloAck struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// True when Main is about to push a StateUpdate because the agent's
	// version is stale.
	StateFollows  bool          `protobuf:"varint,2,opt,name=state_follows,json=stateFollows,proto3" json:"state_follows,omitempty"`
	Settings      *NodeSettings `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HelloAck) GetStateFollows() bool {
	if x != nil {
		return x.StateFollows
	}
	return false
}

func (x *HelloAck) GetSettings() *NodeSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *NodeState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *StateUpdate) GetState() *NodeState {
	if x != nil {
		return x.State
	}
	return nil
}

// UserDelta adds or removes users without touching inbounds, which is what
// keeps Xray from restarting. Applied through Xray's HandlerService.
//
// It is an optimisation, not a second source of truth: every delta carries
// the state version it produces, and a gap in that sequence makes the agent
// ask for a full StateUpdate.
type UserDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	BaseVersion   uint64                 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	Add           []*User                `protobuf:"bytes,3,rep,name=add,proto3" json:"add,omitempty"`
	RemoveUserIds []uint64               `protobuf:"varint,4,rep,packed,name=remove_user_ids,json=removeUserIds,proto3" json:"remove_user_ids,omitempty"`
	// Inbound tags the change applies to; empty means every inbound on the
	// node that supports users.
	InboundTags   []string `protobuf:"bytes,5,rep,name=inbound_tags,json=inboundTags,proto3" json:"inbound_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelta) Reset() {
	*x = UserDelta{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelta) ProtoMessage() {}

func (x *UserDelta) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelta.ProtoReflect.Descriptor instead.
func (*UserDelta) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{23}
}

func (x *UserDelta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UserDelta) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *UserDelta) GetAdd() []*User {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UserDelta) GetRemoveUserIds() []uint64 {
	if x != nil {
		return x.RemoveUserIds
	}
	return nil
}

func (x *UserDelta) GetInboundTags() []string {
	if x != nil {
		return x.InboundTags
	}
	return nil
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{24}
}

func (x *HeartbeatAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=whitenet.node.v1.CommandType" json:"type,omitempty"`
	Core          Core                   `protobuf:"varint,3,opt,name=core,proto3,enum=whitenet.node.v1.Core" json:"core,omitempty"`
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_whitenet_node_v1_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_node_proto_rawDescGZIP(), []int{25}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetCore() Core {
	if x != nil {
		return x.Core
	}
	return Core_CORE_UNSPECIFIED
}

func (x *Command) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

var File_whitenet_node_v1_node_proto protoreflect.FileDescriptor

const file_whitenet_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1bwhitenet/node/v1/node.proto\x12\x10whitenet.node.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cwhitenet/node/v1/state.proto\"\x95\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12.\n" +
	"\x04host\x18\x03 \x01(\v2\x1a.whitenet.node.v1.HostInfoR\x04host\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\xb0\x01\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tnode_uuid\x18\x01 \x01(\tR\bnodeUuid\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\fR\rclientCertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\fR\tcaCertPem\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"2\n" +
	"\x17RenewCertificateRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\"\xbe\x04\n" +
	"\n" +
	"AgentFrame\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.whitenet.node.v1.HelloH\x00R\x05hello\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.whitenet.node.v1.HeartbeatH\x00R\theartbeat\x12E\n" +
	"\rstate_applied\x18\x03 \x01(\v2\x1e.whitenet.node.v1.StateAppliedH\x00R\fstateApplied\x12;\n" +
	"\ametrics\x18\x04 \x01(\v2\x1f.whitenet.node.v1.MetricsReportH\x00R\ametrics\x12;\n" +
	"\atraffic\x18\x05 \x01(\v2\x1f.whitenet.node.v1.TrafficReportH\x00R\atraffic\x125\n" +
	"\x05event\x18\x06 \x01(\v2\x1d.whitenet.node.v1.EventReportH\x00R\x05event\x12H\n" +
	"\x0ecommand_result\x18\a \x01(\v2\x1f.whitenet.node.v1.CommandResultH\x00R\rcommandResult\x129\n" +
	"\tlog_chunk\x18\b \x01(\v2\x1a.whitenet.node.v1.LogChunkH\x00R\blogChunk\x12=\n" +
	"\bchannels\x18\t \x01(\v2\x1f.whitenet.node.v1.ChannelReportH\x00R\bchannelsB\x06\n" +
	"\x04body\"\xb7\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x12.\n" +
	"\x04host\x18\x03 \x01(\v2\x1a.whitenet.node.v1.HostInfoR\x04host\x124\n" +
	"\x05cores\x18\x04 \x01(\v2\x1e.whitenet.node.v1.CoreVersionsR\x05cores\"\xe9\x01\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\x1f\n" +
	"\vpublic_ipv4\x18\x05 \x03(\tR\n" +
	"publicIpv4\x12\x1f\n" +
	"\vpublic_ipv6\x18\x06 \x03(\tR\n" +
	"publicIpv6\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\rR\bcpuCores\x12&\n" +
	"\x0fmem_total_bytes\x18\b \x01(\x04R\rmemTotalBytes\"T\n" +
	"\fCoreVersions\x12\x12\n" +
	"\x04xray\x18\x01 \x01(\tR\x04xray\x12\x14\n" +
	"\x05wndns\x18\x02 \x01(\tR\x05wndns\x12\x1a\n" +
	"\bopenflux\x18\x03 \x01(\tR\bopenflux\"\xbc\x01\n" +
	"\tHeartbeat\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12#\n" +
	"\rstate_version\x18\x02 \x01(\x04R\fstateVersion\x122\n" +
	"\x05cores\x18\x03 \x03(\v2\x1c.whitenet.node.v1.CoreStatusR\x05cores\x12!\n" +
	"\fonline_users\x18\x04 \x01(\rR\vonlineUsers\"\xd1\x01\n" +
	"\n" +
	"CoreStatus\x12*\n" +
	"\x04core\x18\x01 \x01(\x0e2\x16.whitenet.node.v1.CoreR\x04core\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12#\n" +
	"\rrestart_count\x18\x03 \x01(\rR\frestartCount\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\x84\x01\n" +
	"\fStateApplied\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x124\n" +
	"\trestarted\x18\x04 \x03(\x0e2\x16.whitenet.node.v1.CoreR\trestarted\"J\n" +
	"\rMetricsReport\x129\n" +
	"\asamples\x18\x01 \x03(\v2\x1f.whitenet.node.v1.MetricsSampleR\asamples\"\xc9\x03\n" +
	"\rMetricsSample\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x14\n" +
	"\x05load1\x18\x03 \x01(\x01R\x05load1\x12$\n" +
	"\x0emem_used_bytes\x18\x04 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x05 \x01(\x04R\rmemTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x06 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\a \x01(\x04R\x0ediskTotalBytes\x12 \n" +
	"\fnet_rx_bytes\x18\b \x01(\x04R\n" +
	"netRxBytes\x12 \n" +
	"\fnet_tx_bytes\x18\t \x01(\x04R\n" +
	"netTxBytes\x12%\n" +
	"\x0euptime_seconds\x18\n" +
	" \x01(\x04R\ruptimeSeconds\x12!\n" +
	"\fonline_users\x18\v \x01(\rR\vonlineUsers\x12'\n" +
	"\x0ftcp_connections\x18\f \x01(\rR\x0etcpConnections\"\x8e\x01\n" +
	"\rTrafficReport\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x126\n" +
	"\x06deltas\x18\x03 \x03(\v2\x1e.whitenet.node.v1.TrafficDeltaR\x06deltas\"\x92\x01\n" +
	"\fTrafficDelta\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x12!\n" +
	"\fuplink_bytes\x18\x03 \x01(\x04R\vuplinkBytes\x12%\n" +
	"\x0edownlink_bytes\x18\x04 \x01(\x04R\rdownlinkBytes\"x\n" +
	"\rChannelReport\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12;\n" +
	"\bchannels\x18\x02 \x03(\v2\x1f.whitenet.node.v1.ChannelStatusR\bchannels\"\xa6\x01\n" +
	"\rChannelStatus\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x04R\tchannelId\x12%\n" +
	"\x0esession_active\x18\x02 \x01(\bR\rsessionActive\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\">\n" +
	"\vEventReport\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.whitenet.node.v1.EventR\x06events\"\xa9\x01\n" +
	"\x05Event\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12*\n" +
	"\x04core\x18\x05 \x01(\x0e2\x16.whitenet.node.v1.CoreR\x04core\"}\n" +
	"\bLogChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x04core\x18\x02 \x01(\x0e2\x16.whitenet.node.v1.CoreR\x04core\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\"\xcc\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12=\n" +
	"\x04data\x18\x04 \x03(\v2).whitenet.node.v1.CommandResult.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\vServerFrame\x129\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1a.whitenet.node.v1.HelloAckH\x00R\bhelloAck\x12B\n" +
	"\fstate_update\x18\x02 \x01(\v2\x1d.whitenet.node.v1.StateUpdateH\x00R\vstateUpdate\x12<\n" +
	"\n" +
	"user_delta\x18\x03 \x01(\v2\x1b.whitenet.node.v1.UserDeltaH\x00R\tuserDelta\x125\n" +
	"\acommand\x18\x04 \x01(\v2\x19.whitenet.node.v1.CommandH\x00R\acommand\x12E\n" +
	"\rheartbeat_ack\x18\x05 \x01(\v2\x1e.whitenet.node.v1.HeartbeatAckH\x00R\fheartbeatAckB\x06\n" +
	"\x04body\"\xa8\x01\n" +
	"\bHelloAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12#\n" +
	"\rstate_follows\x18\x02 \x01(\bR\fstateFollows\x12:\n" +
	"\bsettings\x18\x03 \x01(\v2\x1e.whitenet.node.v1.NodeSettingsR\bsettings\"@\n" +
	"\vStateUpdate\x121\n" +
	"\x05state\x18\x01 \x01(\v2\x1b.whitenet.node.v1.NodeStateR\x05state\"\xbd\x01\n" +
	"\tUserDelta\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12!\n" +
	"\fbase_version\x18\x02 \x01(\x04R\vbaseVersion\x12(\n" +
	"\x03add\x18\x03 \x03(\v2\x16.whitenet.node.v1.UserR\x03add\x12&\n" +
	"\x0fremove_user_ids\x18\x04 \x03(\x04R\rremoveUserIds\x12!\n" +
	"\finbound_tags\x18\x05 \x03(\tR\vinboundTags\"K\n" +
	"\fHeartbeatAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb1\x02\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.whitenet.node.v1.CommandTypeR\x04type\x12*\n" +
	"\x04core\x18\x03 \x01(\x0e2\x16.whitenet.node.v1.CoreR\x04core\x127\n" +
	"\x04args\x18\x04 \x03(\v2#.whitenet.node.v1.Command.ArgsEntryR\x04args\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xf5\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMMAND_RESTART_CORE\x10\x01\x12\x17\n" +
	"\x13COMMAND_UPDATE_CORE\x10\x02\x12\x18\n" +
	"\x14COMMAND_UPDATE_AGENT\x10\x03\x12\x16\n" +
	"\x12COMMAND_FETCH_LOGS\x10\x04\x12\x12\n" +
	"\x0eCOMMAND_RESYNC\x10\x05\x12\x1d\n" +
	"\x19COMMAND_PROVISION_CHANNEL\x10\x06\x12\x1a\n" +
	"\x16COMMAND_REVOKE_CHANNEL\x10\a\x12\x14\n" +
	"\x10COMMAND_SHUTDOWN\x10\b2a\n" +
	"\fRegistration\x12Q\n" +
	"\bRegister\x12!.whitenet.node.v1.RegisterRequest\x1a\".whitenet.node.v1.RegisterResponse2\xbc\x01\n" +
	"\vNodeControl\x12J\n" +
	"\aSession\x12\x1c.whitenet.node.v1.AgentFrame\x1a\x1d.whitenet.node.v1.ServerFrame(\x010\x01\x12a\n" +
	"\x10RenewCertificate\x12).whitenet.node.v1.RenewCertificateRequest\x1a\".whitenet.node.v1.RegisterResponseB6Z4github.com/thehavlok/whitenet/internal/nodepb;nodepbb\x06proto3"

var (
	file_whitenet_node_v1_node_proto_rawDescOnce sync.Once
	file_whitenet_node_v1_node_proto_rawDescData []byte
)

func file_whitenet_node_v1_node_proto_rawDescGZIP() []byte {
	file_whitenet_node_v1_node_proto_rawDescOnce.Do(func() {
		file_whitenet_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitenet_node_v1_node_proto_rawDesc), len(file_whitenet_node_v1_node_proto_rawDesc)))
	})
	return file_whitenet_node_v1_node_proto_rawDescData
}

var file_whitenet_node_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_whitenet_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_whitenet_node_v1_node_proto_goTypes = []any{
	(CommandType)(0),                // 0: whitenet.node.v1.CommandType
	(*RegisterRequest)(nil),         // 1: whitenet.node.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 2: whitenet.node.v1.RegisterResponse
	(*RenewCertificateRequest)(nil), // 3: whitenet.node.v1.RenewCertificateRequest
	(*AgentFrame)(nil),              // 4: whitenet.node.v1.AgentFrame
	(*Hello)(nil),                   // 5: whitenet.node.v1.Hello
	(*HostInfo)(nil),                // 6: whitenet.node.v1.HostInfo
	(*CoreVersions)(nil),            // 7: whitenet.node.v1.CoreVersions
	(*Heartbeat)(nil),               // 8: whitenet.node.v1.Heartbeat
	(*CoreStatus)(nil),              // 9: whitenet.node.v1.CoreStatus
	(*StateApplied)(nil),            // 10: whitenet.node.v1.StateApplied
	(*MetricsReport)(nil),           // 11: whitenet.node.v1.MetricsReport
	(*MetricsSample)(nil),           // 12: whitenet.node.v1.MetricsSample
	(*TrafficReport)(nil),           // 13: whitenet.node.v1.TrafficReport
	(*TrafficDelta)(nil),            // 14: whitenet.node.v1.TrafficDelta
	(*ChannelReport)(nil),           // 15: whitenet.node.v1.ChannelReport
	(*ChannelStatus)(nil),           // 16: whitenet.node.v1.ChannelStatus
	(*EventReport)(nil),             // 17: whitenet.node.v1.EventReport
	(*Event)(nil),                   // 18: whitenet.node.v1.Event
	(*LogChunk)(nil),                // 19: whitenet.node.v1.LogChunk
	(*CommandResult)(nil),           // 20: whitenet.node.v1.CommandResult
	(*ServerFrame)(nil),             // 21: whitenet.node.v1.ServerFrame
	(*HelloAck)(nil),                // 22: whitenet.node.v1.HelloAck
	(*StateUpdate)(nil),             // 23: whitenet.node.v1.StateUpdate
	(*UserDelta)(nil),               // 24: whitenet.node.v1.UserDelta
	(*HeartbeatAck)(nil),            // 25: whitenet.node.v1.HeartbeatAck
	(*Command)(nil),                 // 26: whitenet.node.v1.Command
	nil,                             // 27: whitenet.node.v1.CommandResult.DataEntry
	nil,                             // 28: whitenet.node.v1.Command.ArgsEntry
	(*timestamppb.Timestamp)(nil),   // 29: google.protobuf.Timestamp
	(Core)(0),                       // 30: whitenet.node.v1.Core
	(*NodeSettings)(nil),            // 31: whitenet.node.v1.NodeSettings
	(*NodeState)(nil),               // 32: whitenet.node.v1.NodeState
	(*User)(nil),                    // 33: whitenet.node.v1.User
}
var file_whitenet_node_v1_node_proto_depIdxs = []int32{
	6,  // 0: whitenet.node.v1.RegisterRequest.host:type_name -> whitenet.node.v1.HostInfo
	29, // 1: whitenet.node.v1.RegisterResponse.not_after:type_name -> google.protobuf.Timestamp
	5,  // 2: whitenet.node.v1.AgentFrame.hello:type_name -> whitenet.node.v1.Hello
	8,  // 3: whitenet.node.v1.AgentFrame.heartbeat:type_name -> whitenet.node.v1.Heartbeat
	10, // 4: whitenet.node.v1.AgentFrame.state_applied:type_name -> whitenet.node.v1.StateApplied
	11, // 5: whitenet.node.v1.AgentFrame.metrics:type_name -> whitenet.node.v1.MetricsReport
	13, // 6: whitenet.node.v1.AgentFrame.traffic:type_name -> whitenet.node.v1.TrafficReport
	17, // 7: whitenet.node.v1.AgentFrame.event:type_name -> whitenet.node.v1.EventReport
	20, // 8: whitenet.node.v1.AgentFrame.command_result:type_name -> whitenet.node.v1.CommandResult
	19, // 9: whitenet.node.v1.AgentFrame.log_chunk:type_name -> whitenet.node.v1.LogChunk
	15, // 10: whitenet.node.v1.AgentFrame.channels:type_name -> whitenet.node.v1.ChannelReport
	6,  // 11: whitenet.node.v1.Hello.host:type_name -> whitenet.node.v1.HostInfo
	7,  // 12: whitenet.node.v1.Hello.cores:type_name -> whitenet.node.v1.CoreVersions
	29, // 13: whitenet.node.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	9,  // 14: whitenet.node.v1.Heartbeat.cores:type_name -> whitenet.node.v1.CoreStatus
	30, // 15: whitenet.node.v1.CoreStatus.core:type_name -> whitenet.node.v1.Core
	29, // 16: whitenet.node.v1.CoreStatus.started_at:type_name -> google.protobuf.Timestamp
	30, // 17: whitenet.node.v1.StateApplied.restarted:type_name -> whitenet.node.v1.Core
	12, // 18: whitenet.node.v1.MetricsReport.samples:type_name -> whitenet.node.v1.MetricsSample
	29, // 19: whitenet.node.v1.MetricsSample.at:type_name -> google.protobuf.Timestamp
	29, // 20: whitenet.node.v1.TrafficReport.at:type_name -> google.protobuf.Timestamp
	14, // 21: whitenet.node.v1.TrafficReport.deltas:type_name -> whitenet.node.v1.TrafficDelta
	29, // 22: whitenet.node.v1.ChannelReport.at:type_name -> google.protobuf.Timestamp
	16, // 23: whitenet.node.v1.ChannelReport.channels:type_name -> whitenet.node.v1.ChannelStatus
	29, // 24: whitenet.node.v1.ChannelStatus.since:type_name -> google.protobuf.Timestamp
	18, // 25: whitenet.node.v1.EventReport.events:type_name -> whitenet.node.v1.Event
	29, // 26: whitenet.node.v1.Event.at:type_name -> google.protobuf.Timestamp
	30, // 27: whitenet.node.v1.Event.core:type_name -> whitenet.node.v1.Core
	30, // 28: whitenet.node.v1.LogChunk.core:type_name -> whitenet.node.v1.Core
	27, // 29: whitenet.node.v1.CommandResult.data:type_name -> whitenet.node.v1.CommandResult.DataEntry
	22, // 30: whitenet.node.v1.ServerFrame.hello_ack:type_name -> whitenet.node.v1.HelloAck
	23, // 31: whitenet.node.v1.ServerFrame.state_update:type_name -> whitenet.node.v1.StateUpdate
	24, // 32: whitenet.node.v1.ServerFrame.user_delta:type_name -> whitenet.node.v1.UserDelta
	26, // 33: whitenet.node.v1.ServerFrame.command:type_name -> whitenet.node.v1.Command
	25, // 34: whitenet.node.v1.ServerFrame.heartbeat_ack:type_name -> whitenet.node.v1.HeartbeatAck
	29, // 35: whitenet.node.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	31, // 36: whitenet.node.v1.HelloAck.settings:type_name -> whitenet.node.v1.NodeSettings
	32, // 37: whitenet.node.v1.StateUpdate.state:type_name -> whitenet.node.v1.NodeState
	33, // 38: whitenet.node.v1.UserDelta.add:type_name -> whitenet.node.v1.User
	29, // 39: whitenet.node.v1.HeartbeatAck.server_time:type_name -> google.protobuf.Timestamp
	0,  // 40: whitenet.node.v1.Command.type:type_name -> whitenet.node.v1.CommandType
	30, // 41: whitenet.node.v1.Command.core:type_name -> whitenet.node.v1.Core
	28, // 42: whitenet.node.v1.Command.args:type_name -> whitenet.node.v1.Command.ArgsEntry
	29, // 43: whitenet.node.v1.Command.deadline:type_name -> google.protobuf.Timestamp
	1,  // 44: whitenet.node.v1.Registration.Register:input_type -> whitenet.node.v1.RegisterRequest
	4,  // 45: whitenet.node.v1.NodeControl.Session:input_type -> whitenet.node.v1.AgentFrame
	3,  // 46: whitenet.node.v1.NodeControl.RenewCertificate:input_type -> whitenet.node.v1.RenewCertificateRequest
	2,  // 47: whitenet.node.v1.Registration.Register:output_type -> whitenet.node.v1.RegisterResponse
	21, // 48: whitenet.node.v1.NodeControl.Session:output_type -> whitenet.node.v1.ServerFrame
	2,  // 49: whitenet.node.v1.NodeControl.RenewCertificate:output_type -> whitenet.node.v1.RegisterResponse
	47, // [47:50] is the sub-list for method output_type
	44, // [44:47] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_whitenet_node_v1_node_proto_init() }
func file_whitenet_node_v1_node_proto_init() {
	if File_whitenet_node_v1_node_proto != nil {
		return
	}
	file_whitenet_node_v1_state_proto_init()
	file_whitenet_node_v1_node_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentFrame_Hello)(nil),
		(*AgentFrame_Heartbeat)(nil),
		(*AgentFrame_StateApplied)(nil),
		(*AgentFrame_Metrics)(nil),
		(*AgentFrame_Traffic)(nil),
		(*AgentFrame_Event)(nil),
		(*AgentFrame_CommandResult)(nil),
		(*AgentFrame_LogChunk)(nil),
		(*AgentFrame_Channels)(nil),
	}
	file_whitenet_node_v1_node_proto_msgTypes[20].OneofWrappers = []any{
		(*ServerFrame_HelloAck)(nil),
		(*ServerFrame_StateUpdate)(nil),
		(*ServerFrame_UserDelta)(nil),
		(*ServerFrame_Command)(nil),
		(*ServerFrame_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitenet_node_v1_node_proto_rawDesc), len(file_whitenet_node_v1_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_whitenet_node_v1_node_proto_goTypes,
		DependencyIndexes: file_whitenet_node_v1_node_proto_depIdxs,
		EnumInfos:         file_whitenet_node_v1_node_proto_enumTypes,
		MessageInfos:      file_whitenet_node_v1_node_proto_msgTypes,
	}.Build()
	File_whitenet_node_v1_node_proto = out.File
	file_whitenet_node_v1_node_proto_goTypes = nil
	file_whitenet_node_v1_node_proto_depIdxs = nil
}
