// Desired state of a single node.
//
// Main owns this structure: it is rendered from the database whenever
// something that affects a node changes, stamped with a monotonically
// increasing version, and handed to the agent. The agent never computes
// state of its own - it only applies what it is given and reports back
// which version it managed to apply.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: whitenet/node/v1/state.proto

package nodepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core is one of the three engines an agent supervises on a node.
type Core int32

const (
	Core_CORE_UNSPECIFIED Core = 0
	Core_CORE_XRAY        Core = 1 // xray-core, every classic protocol
	Core_CORE_WNDNS       Core = 2 // WhiteNet DNS tunnel (masterdnsvpn)
	Core_CORE_OPENFLUX    Core = 3 // OpenFlux exit node
)

// Enum value maps for Core.
var (
	Core_name = map[int32]string{
		0: "CORE_UNSPECIFIED",
		1: "CORE_XRAY",
		2: "CORE_WNDNS",
		3: "CORE_OPENFLUX",
	}
	Core_value = map[string]int32{
		"CORE_UNSPECIFIED": 0,
		"CORE_XRAY":        1,
		"CORE_WNDNS":       2,
		"CORE_OPENFLUX":    3,
	}
)

func (x Core) Enum() *Core {
	p := new(Core)
	*p = x
	return p
}

func (x Core) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Core) Descriptor() protoreflect.EnumDescriptor {
	return file_whitenet_node_v1_state_proto_enumTypes[0].Descriptor()
}

func (Core) Type() protoreflect.EnumType {
	return &file_whitenet_node_v1_state_proto_enumTypes[0]
}

func (x Core) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Core.Descriptor instead.
func (Core) EnumDescriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{0}
}

// Protocol identifies what an inbound speaks. Everything up to
// PROTOCOL_HYSTERIA2 is served by xray-core; PROTOCOL_WNDNS is served by the
// DNS tunnel. OpenFlux is not an inbound at all (see OpenFluxConfig) because
// it has no listening port and no multi-user model.
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED      Protocol = 0
	Protocol_PROTOCOL_VLESS            Protocol = 1
	Protocol_PROTOCOL_VMESS            Protocol = 2
	Protocol_PROTOCOL_TROJAN           Protocol = 3
	Protocol_PROTOCOL_SHADOWSOCKS      Protocol = 4
	Protocol_PROTOCOL_SHADOWSOCKS_2022 Protocol = 5
	Protocol_PROTOCOL_HYSTERIA2        Protocol = 6
	Protocol_PROTOCOL_WNDNS            Protocol = 7
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_VLESS",
		2: "PROTOCOL_VMESS",
		3: "PROTOCOL_TROJAN",
		4: "PROTOCOL_SHADOWSOCKS",
		5: "PROTOCOL_SHADOWSOCKS_2022",
		6: "PROTOCOL_HYSTERIA2",
		7: "PROTOCOL_WNDNS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED":      0,
		"PROTOCOL_VLESS":            1,
		"PROTOCOL_VMESS":            2,
		"PROTOCOL_TROJAN":           3,
		"PROTOCOL_SHADOWSOCKS":      4,
		"PROTOCOL_SHADOWSOCKS_2022": 5,
		"PROTOCOL_HYSTERIA2":        6,
		"PROTOCOL_WNDNS":            7,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_whitenet_node_v1_state_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_whitenet_node_v1_state_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{1}
}

// NodeState is the complete, self-contained description of what a node must
// be running. It is idempotent: applying the same state twice is a no-op,
// and a node that was offline for a week converges by applying the newest
// state it receives.
type NodeState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version increases strictly monotonically per node. The agent persists it
	// and reports it on reconnect so Main can skip a resend.
	Version  uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	NodeUuid string `protobuf:"bytes,2,opt,name=node_uuid,json=nodeUuid,proto3" json:"node_uuid,omitempty"`
	// Inbounds the node must serve, across all cores.
	Inbounds []*Inbound `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	// Users allowed on this node, already filtered by group membership and
	// status. An empty list is legitimate and means "serve no one".
	Users []*User `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	// OpenFlux exit configuration; absent means the OpenFlux core stays down.
	Openflux *OpenFluxConfig `protobuf:"bytes,5,opt,name=openflux,proto3" json:"openflux,omitempty"`
	// Knobs that are not tied to a single inbound.
	Settings      *NodeSettings `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeState) GetNodeUuid() string {
	if x != nil {
		return x.NodeUuid
	}
	return ""
}

func (x *NodeState) GetInbounds() []*Inbound {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *NodeState) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *NodeState) GetOpenflux() *OpenFluxConfig {
	if x != nil {
		return x.Openflux
	}
	return nil
}

func (x *NodeState) GetSettings() *NodeSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type NodeSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How often the agent sends a heartbeat. Main is the single source of
	// truth for the interval so it can be retuned centrally.
	HeartbeatIntervalSeconds uint32 `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	// How often traffic counters are read from Xray and shipped to Main.
	TrafficReportIntervalSeconds uint32 `protobuf:"varint,2,opt,name=traffic_report_interval_seconds,json=trafficReportIntervalSeconds,proto3" json:"traffic_report_interval_seconds,omitempty"`
	// How often host metrics are sampled and shipped.
	MetricsIntervalSeconds uint32 `protobuf:"varint,3,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	// Xray log level: debug, info, warning, error, none.
	XrayLogLevel string `protobuf:"bytes,4,opt,name=xray_log_level,json=xrayLogLevel,proto3" json:"xray_log_level,omitempty"`
	// Pinned core versions; empty means "whatever is installed".
	XrayVersion     string `protobuf:"bytes,5,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	OpenfluxVersion string `protobuf:"bytes,6,opt,name=openflux_version,json=openfluxVersion,proto3" json:"openflux_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeSettings) Reset() {
	*x = NodeSettings{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSettings) ProtoMessage() {}

func (x *NodeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSettings.ProtoReflect.Descriptor instead.
func (*NodeSettings) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSettings) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *NodeSettings) GetTrafficReportIntervalSeconds() uint32 {
	if x != nil {
		return x.TrafficReportIntervalSeconds
	}
	return 0
}

func (x *NodeSettings) GetMetricsIntervalSeconds() uint32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

func (x *NodeSettings) GetXrayLogLevel() string {
	if x != nil {
		return x.XrayLogLevel
	}
	return ""
}

func (x *NodeSettings) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *NodeSettings) GetOpenfluxVersion() string {
	if x != nil {
		return x.OpenfluxVersion
	}
	return ""
}

// Inbound is one listening endpoint. Params and Secrets are deliberately
// loose maps rather than a per-protocol message: Main already validated them
// against the protocol's schema, and keeping the wire format open means a new
// Xray knob does not require a proto change plus an agent rollout.
type Inbound struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity. Tag is what Xray sees and what traffic counters are
	// keyed by, so it must never change for a live inbound.
	Tag           string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Id            uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      Protocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=whitenet.node.v1.Protocol" json:"protocol,omitempty"`
	Core          Core     `protobuf:"varint,4,opt,name=core,proto3,enum=whitenet.node.v1.Core" json:"core,omitempty"`
	Enabled       bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ListenPort    uint32   `protobuf:"varint,6,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ListenAddress string   `protobuf:"bytes,7,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"` // empty means all interfaces
	// Transport and TLS, e.g. network=raw|xhttp|ws|grpc|httpupgrade|kcp,
	// security=none|tls|reality. Protocol-specific keys live here too
	// (sni, dest, fingerprint, path, serviceName, obfs, ...).
	Params map[string]string `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secret material: reality private key, certificates, the DNS tunnel's
	// encryption key. Encrypted at rest on Main and only ever sent over mTLS.
	Secrets map[string]string `protobuf:"bytes,9,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// For PROTOCOL_WNDNS: the tag of the Xray inbound this tunnel forwards
	// every stream to. That chain is what gives the DNS protocol per-user
	// authentication, traffic accounting and limits, none of which the DNS
	// protocol has on its own.
	ForwardToTag  string `protobuf:"bytes,10,opt,name=forward_to_tag,json=forwardToTag,proto3" json:"forward_to_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inbound) Reset() {
	*x = Inbound{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inbound) ProtoMessage() {}

func (x *Inbound) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inbound.ProtoReflect.Descriptor instead.
func (*Inbound) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *Inbound) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Inbound) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Inbound) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *Inbound) GetCore() Core {
	if x != nil {
		return x.Core
	}
	return Core_CORE_UNSPECIFIED
}

func (x *Inbound) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Inbound) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *Inbound) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *Inbound) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Inbound) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Inbound) GetForwardToTag() string {
	if x != nil {
		return x.ForwardToTag
	}
	return ""
}

// User is one account as a node needs to see it: identity plus the secrets
// required by whichever protocols the node serves. Limits are not sent -
// enforcement lives on Main, which simply removes the user from the state
// when they run out.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid  string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Email is Xray's user key; it is what StatsService reports traffic under.
	// Format: "<id>.<uuid-prefix>@whitenet" - synthetic, never a real address.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// VLESS/VMess identity.
	VlessUuid string `protobuf:"bytes,4,opt,name=vless_uuid,json=vlessUuid,proto3" json:"vless_uuid,omitempty"`
	// Trojan and Hysteria2 share one password per user.
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// Shadowsocks (including 2022) key/password, base64 for 2022 methods.
	SsPassword string `protobuf:"bytes,6,opt,name=ss_password,json=ssPassword,proto3" json:"ss_password,omitempty"`
	// Per-user Xray flow for VLESS, e.g. xtls-rprx-vision. Usually empty and
	// taken from the inbound.
	Flow          string `protobuf:"bytes,7,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetVlessUuid() string {
	if x != nil {
		return x.VlessUuid
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetSsPassword() string {
	if x != nil {
		return x.SsPassword
	}
	return ""
}

func (x *User) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

// OpenFluxConfig describes the exit process and its channel pool.
//
// OpenFlux has no user model and exactly one client per session, so a node
// serves it as a pool of pre-provisioned channels that Main leases out. The
// agent's job is to keep the exit process alive for every enabled channel and
// to report which channels are actually carrying a session.
type OpenFluxConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// l3 (Linux, raw sockets, needs root) or l4 (gVisor, portable).
	Mode          string             `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Channels      []*OpenFluxChannel `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFluxConfig) Reset() {
	*x = OpenFluxConfig{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFluxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFluxConfig) ProtoMessage() {}

func (x *OpenFluxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFluxConfig.ProtoReflect.Descriptor instead.
func (*OpenFluxConfig) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *OpenFluxConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OpenFluxConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OpenFluxConfig) GetChannels() []*OpenFluxChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type OpenFluxChannel struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid    string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Enabled bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Transport type: yandex, vyandex, boards, oneme, cupsonline, mailru,
	// direct, phpbox.
	Transport string `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	// The rendezvous: document URL, room, or listen address for direct.
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// Transport-specific extras (direct_listen, share_host, cookies, ...).
	Params map[string]string `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// AES-256-GCM shared secret, hex, and the KDF context. Rotating the key is
	// how Main revokes a channel: the running session stops decrypting.
	EncryptionKey  string `protobuf:"bytes,7,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	SessionContext string `protobuf:"bytes,8,opt,name=session_context,json=sessionContext,proto3" json:"session_context,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenFluxChannel) Reset() {
	*x = OpenFluxChannel{}
	mi := &file_whitenet_node_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFluxChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFluxChannel) ProtoMessage() {}

func (x *OpenFluxChannel) ProtoReflect() protoreflect.Message {
	mi := &file_whitenet_node_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFluxChannel.ProtoReflect.Descriptor instead.
func (*OpenFluxChannel) Descriptor() ([]byte, []int) {
	return file_whitenet_node_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *OpenFluxChannel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OpenFluxChannel) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *OpenFluxChannel) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OpenFluxChannel) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *OpenFluxChannel) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OpenFluxChannel) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *OpenFluxChannel) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *OpenFluxChannel) GetSessionContext() string {
	if x != nil {
		return x.SessionContext
	}
	return ""
}

var File_whitenet_node_v1_state_proto protoreflect.FileDescriptor

const file_whitenet_node_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1cwhitenet/node/v1/state.proto\x12\x10whitenet.node.v1\"\xa1\x02\n" +
	"\tNodeState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1b\n" +
	"\tnode_uuid\x18\x02 \x01(\tR\bnodeUuid\x125\n" +
	"\binbounds\x18\x03 \x03(\v2\x19.whitenet.node.v1.InboundR\binbounds\x12,\n" +
	"\x05users\x18\x04 \x03(\v2\x16.whitenet.node.v1.UserR\x05users\x12<\n" +
	"\bopenflux\x18\x05 \x01(\v2 .whitenet.node.v1.OpenFluxConfigR\bopenflux\x12:\n" +
	"\bsettings\x18\x06 \x01(\v2\x1e.whitenet.node.v1.NodeSettingsR\bsettings\"\xc1\x02\n" +
	"\fNodeSettings\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\rR\x18heartbeatIntervalSeconds\x12E\n" +
	"\x1ftraffic_report_interval_seconds\x18\x02 \x01(\rR\x1ctrafficReportIntervalSeconds\x128\n" +
	"\x18metrics_interval_seconds\x18\x03 \x01(\rR\x16metricsIntervalSeconds\x12$\n" +
	"\x0exray_log_level\x18\x04 \x01(\tR\fxrayLogLevel\x12!\n" +
	"\fxray_version\x18\x05 \x01(\tR\vxrayVersion\x12)\n" +
	"\x10openflux_version\x18\x06 \x01(\tR\x0fopenfluxVersion\"\x8f\x04\n" +
	"\aInbound\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x126\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x1a.whitenet.node.v1.ProtocolR\bprotocol\x12*\n" +
	"\x04core\x18\x04 \x01(\x0e2\x16.whitenet.node.v1.CoreR\x04core\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1f\n" +
	"\vlisten_port\x18\x06 \x01(\rR\n" +
	"listenPort\x12%\n" +
	"\x0elisten_address\x18\a \x01(\tR\rlistenAddress\x12=\n" +
	"\x06params\x18\b \x03(\v2%.whitenet.node.v1.Inbound.ParamsEntryR\x06params\x12@\n" +
	"\asecrets\x18\t \x03(\v2&.whitenet.node.v1.Inbound.SecretsEntryR\asecrets\x12$\n" +
	"\x0eforward_to_tag\x18\n" +
	" \x01(\tR\fforwardToTag\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"vless_uuid\x18\x04 \x01(\tR\tvlessUuid\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1f\n" +
	"\vss_password\x18\x06 \x01(\tR\n" +
	"ssPassword\x12\x12\n" +
	"\x04flow\x18\a \x01(\tR\x04flow\"}\n" +
	"\x0eOpenFluxConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12=\n" +
	"\bchannels\x18\x03 \x03(\v2!.whitenet.node.v1.OpenFluxChannelR\bchannels\"\xd1\x02\n" +
	"\x0fOpenFluxChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransport\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12E\n" +
	"\x06params\x18\x06 \x03(\v2-.whitenet.node.v1.OpenFluxChannel.ParamsEntryR\x06params\x12%\n" +
	"\x0eencryption_key\x18\a \x01(\tR\rencryptionKey\x12'\n" +
	"\x0fsession_context\x18\b \x01(\tR\x0esessionContext\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*N\n" +
	"\x04Core\x12\x14\n" +
	"\x10CORE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCORE_XRAY\x10\x01\x12\x0e\n" +
	"\n" +
	"CORE_WNDNS\x10\x02\x12\x11\n" +
	"\rCORE_OPENFLUX\x10\x03*\xc6\x01\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePROTOCOL_VLESS\x10\x01\x12\x12\n" +
	"\x0ePROTOCOL_VMESS\x10\x02\x12\x13\n" +
	"\x0fPROTOCOL_TROJAN\x10\x03\x12\x18\n" +
	"\x14PROTOCOL_SHADOWSOCKS\x10\x04\x12\x1d\n" +
	"\x19PROTOCOL_SHADOWSOCKS_2022\x10\x05\x12\x16\n" +
	"\x12PROTOCOL_HYSTERIA2\x10\x06\x12\x12\n" +
	"\x0ePROTOCOL_WNDNS\x10\aB6Z4github.com/thehavlok/whitenet/internal/nodepb;nodepbb\x06proto3"

var (
	file_whitenet_node_v1_state_proto_rawDescOnce sync.Once
	file_whitenet_node_v1_state_proto_rawDescData []byte
)

func file_whitenet_node_v1_state_proto_rawDescGZIP() []byte {
	file_whitenet_node_v1_state_proto_rawDescOnce.Do(func() {
		file_whitenet_node_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitenet_node_v1_state_proto_rawDesc), len(file_whitenet_node_v1_state_proto_rawDesc)))
	})
	return file_whitenet_node_v1_state_proto_rawDescData
}

var file_whitenet_node_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_whitenet_node_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_whitenet_node_v1_state_proto_goTypes = []any{
	(Core)(0),               // 0: whitenet.node.v1.Core
	(Protocol)(0),           // 1: whitenet.node.v1.Protocol
	(*NodeState)(nil),       // 2: whitenet.node.v1.NodeState
	(*NodeSettings)(nil),    // 3: whitenet.node.v1.NodeSettings
	(*Inbound)(nil),         // 4: whitenet.node.v1.Inbound
	(*User)(nil),            // 5: whitenet.node.v1.User
	(*OpenFluxConfig)(nil),  // 6: whitenet.node.v1.OpenFluxConfig
	(*OpenFluxChannel)(nil), // 7: whitenet.node.v1.OpenFluxChannel
	nil,                     // 8: whitenet.node.v1.Inbound.ParamsEntry
	nil,                     // 9: whitenet.node.v1.Inbound.SecretsEntry
	nil,                     // 10: whitenet.node.v1.OpenFluxChannel.ParamsEntry
}
var file_whitenet_node_v1_state_proto_depIdxs = []int32{
	4,  // 0: whitenet.node.v1.NodeState.inbounds:type_name -> whitenet.node.v1.Inbound
	5,  // 1: whitenet.node.v1.NodeState.users:type_name -> whitenet.node.v1.User
	6,  // 2: whitenet.node.v1.NodeState.openflux:type_name -> whitenet.node.v1.OpenFluxConfig
	3,  // 3: whitenet.node.v1.NodeState.settings:type_name -> whitenet.node.v1.NodeSettings
	1,  // 4: whitenet.node.v1.Inbound.protocol:type_name -> whitenet.node.v1.Protocol
	0,  // 5: whitenet.node.v1.Inbound.core:type_name -> whitenet.node.v1.Core
	8,  // 6: whitenet.node.v1.Inbound.params:type_name -> whitenet.node.v1.Inbound.ParamsEntry
	9,  // 7: whitenet.node.v1.Inbound.secrets:type_name -> whitenet.node.v1.Inbound.SecretsEntry
	7,  // 8: whitenet.node.v1.OpenFluxConfig.channels:type_name -> whitenet.node.v1.OpenFluxChannel
	10, // 9: whitenet.node.v1.OpenFluxChannel.params:type_name -> whitenet.node.v1.OpenFluxChannel.ParamsEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_whitenet_node_v1_state_proto_init() }
func file_whitenet_node_v1_state_proto_init() {
	if File_whitenet_node_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitenet_node_v1_state_proto_rawDesc), len(file_whitenet_node_v1_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_whitenet_node_v1_state_proto_goTypes,
		DependencyIndexes: file_whitenet_node_v1_state_proto_depIdxs,
		EnumInfos:         file_whitenet_node_v1_state_proto_enumTypes,
		MessageInfos:      file_whitenet_node_v1_state_proto_msgTypes,
	}.Build()
	File_whitenet_node_v1_state_proto = out.File
	file_whitenet_node_v1_state_proto_goTypes = nil
	file_whitenet_node_v1_state_proto_depIdxs = nil
}
