package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jmoiron/sqlx"
)

// ErrDeviceLimit is returned when a new device would exceed the user's limit.
// The subscription endpoint turns it into a refusal the app can explain.
var ErrDeviceLimit = errors.New("store: the user's device limit is reached")

const userColumns = `id, uuid, name, comment, sub_token, sub_token_issued_at,
	vless_uuid, password, ss_password,
	expires_at, traffic_limit, traffic_used, devices_limit,
	reset_strategy, next_reset_at, last_reset_at, status,
	last_sub_fetch_at, created_at, updated_at`

// NewSubToken returns a fresh subscription token: 24 random bytes, URL-safe.
//
// It is a bearer credential in a URL, so it has to survive being copied by
// hand and pasted into a phone, which rules out anything with punctuation.
func NewSubToken() (string, error) {
	raw := make([]byte, 24)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("store: generate subscription token: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// NewUser is what the API passes to create a user. The credentials are
// generated by the caller, because they have to be encrypted with the panel's
// master key before they reach the database.
type NewUser struct {
	Name          string
	Comment       string
	VLESSUUID     string
	Password      []byte // encrypted
	SSPassword    []byte // encrypted
	ExpiresAt     *time.Time
	TrafficLimit  uint64
	DevicesLimit  uint32
	ResetStrategy string
	GroupIDs      []uint64
}

// CreateUser inserts a user and their group assignments.
func (s *Store) CreateUser(ctx context.Context, u NewUser) (*User, error) {
	token, err := NewSubToken()
	if err != nil {
		return nil, err
	}
	strategy := u.ResetStrategy
	if strategy == "" {
		strategy = "manual"
	}

	var id uint64
	err = s.Tx(ctx, func(tx *sqlx.Tx) error {
		res, err := tx.ExecContext(ctx,
			`INSERT INTO users (uuid, name, comment, sub_token, vless_uuid, password, ss_password,
				expires_at, traffic_limit, devices_limit, reset_strategy)
			 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
			uuid.NewString(), u.Name, nullString(u.Comment), token, u.VLESSUUID,
			u.Password, u.SSPassword, timeOrNull(u.ExpiresAt),
			u.TrafficLimit, u.DevicesLimit, strategy)
		if err != nil {
			return fmt.Errorf("store: create user: %w", err)
		}
		lastID, _ := res.LastInsertId()
		id = uint64(lastID)
		if err := setUserGroupsTx(ctx, tx, id, u.GroupIDs); err != nil {
			return err
		}
		// Every node in the user's groups now has one more user to serve.
		return bumpNodesForUserGroupsTx(ctx, tx, u.GroupIDs)
	})
	if err != nil {
		return nil, err
	}
	return s.UserByID(ctx, id)
}

// UserByID reads one user.
func (s *Store) UserByID(ctx context.Context, id uint64) (*User, error) {
	var u User
	err := s.DB.GetContext(ctx, &u, `SELECT `+userColumns+` FROM users WHERE id = ?`, id)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("store: user %d: %w", id, ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("store: user %d: %w", id, err)
	}
	return &u, nil
}

// UserBySubToken reads the user a subscription token belongs to. This is the
// hot path of the subscription endpoint, so the column is unique and indexed.
func (s *Store) UserBySubToken(ctx context.Context, token string) (*User, error) {
	var u User
	err := s.DB.GetContext(ctx, &u, `SELECT `+userColumns+` FROM users WHERE sub_token = ?`, token)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("store: subscription token: %w", ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("store: subscription token: %w", err)
	}
	return &u, nil
}

// UserFilter narrows a list.
type UserFilter struct {
	// Search matches the name or the comment.
	Search string
	// Status, when set, matches exactly.
	Status string
	// GroupID, when set, matches users in that group.
	GroupID uint64
	// ExpiringWithin lists users whose time runs out soon.
	ExpiringWithin time.Duration
	Limit          int
	Offset         int
}

// ListUsers returns users matching the filter, and the total that matched
// before the limit, for the admin UI's pagination.
func (s *Store) ListUsers(ctx context.Context, filter UserFilter) ([]User, int, error) {
	var where []string
	var args []any

	if filter.Search != "" {
		where = append(where, "(u.name LIKE ? OR u.comment LIKE ?)")
		like := "%" + filter.Search + "%"
		args = append(args, like, like)
	}
	if filter.Status != "" {
		where = append(where, "u.status = ?")
		args = append(args, filter.Status)
	}
	if filter.GroupID != 0 {
		where = append(where, "EXISTS (SELECT 1 FROM user_group_members m WHERE m.user_id = u.id AND m.group_id = ?)")
		args = append(args, filter.GroupID)
	}
	if filter.ExpiringWithin > 0 {
		where = append(where, "u.expires_at IS NOT NULL AND u.expires_at <= ?")
		args = append(args, time.Now().UTC().Add(filter.ExpiringWithin))
	}

	clause := ""
	if len(where) > 0 {
		clause = " WHERE " + strings.Join(where, " AND ")
	}

	var total int
	if err := s.DB.GetContext(ctx, &total, `SELECT COUNT(*) FROM users u`+clause, args...); err != nil {
		return nil, 0, fmt.Errorf("store: count users: %w", err)
	}

	query := `SELECT ` + prefixColumns(userColumns, "u") + ` FROM users u` + clause + ` ORDER BY u.name, u.id`
	if filter.Limit > 0 {
		query += fmt.Sprintf(" LIMIT %d OFFSET %d", filter.Limit, filter.Offset)
	}
	var out []User
	if err := s.DB.SelectContext(ctx, &out, query, args...); err != nil {
		return nil, 0, fmt.Errorf("store: list users: %w", err)
	}
	return out, total, nil
}

// UserUpdate is the partial update the API accepts.
type UserUpdate struct {
	Name          *string
	Comment       *string
	ExpiresAt     **time.Time // a pointer to a pointer, so "set to never" is expressible
	TrafficLimit  *uint64
	DevicesLimit  *uint32
	ResetStrategy *string
	Status        *string
	GroupIDs      *[]uint64
}

// UpdateUser applies an update and bumps the nodes that serve the user.
func (s *Store) UpdateUser(ctx context.Context, id uint64, update UserUpdate) (*User, error) {
	err := s.Tx(ctx, func(tx *sqlx.Tx) error {
		// The old groups matter as much as the new ones: a node the user is
		// leaving has to stop serving them.
		oldGroups, err := userGroupIDsTx(ctx, tx, id)
		if err != nil {
			return err
		}

		var sets []string
		var args []any
		add := func(column string, value any) {
			sets = append(sets, column+" = ?")
			args = append(args, value)
		}
		if update.Name != nil {
			add("name", *update.Name)
		}
		if update.Comment != nil {
			add("comment", nullString(*update.Comment))
		}
		if update.ExpiresAt != nil {
			add("expires_at", timeOrNull(*update.ExpiresAt))
		}
		if update.TrafficLimit != nil {
			add("traffic_limit", *update.TrafficLimit)
		}
		if update.DevicesLimit != nil {
			add("devices_limit", *update.DevicesLimit)
		}
		if update.ResetStrategy != nil {
			add("reset_strategy", *update.ResetStrategy)
		}
		if update.Status != nil {
			add("status", *update.Status)
		}
		if len(sets) > 0 {
			args = append(args, id)
			if _, err := tx.ExecContext(ctx,
				`UPDATE users SET `+strings.Join(sets, ", ")+` WHERE id = ?`, args...); err != nil {
				return fmt.Errorf("store: update user %d: %w", id, err)
			}
		}

		affected := oldGroups
		if update.GroupIDs != nil {
			if err := setUserGroupsTx(ctx, tx, id, *update.GroupIDs); err != nil {
				return err
			}
			affected = append(affected, *update.GroupIDs...)
		}
		// Only the things a node sees are worth a bump: the status decides
		// whether the user is in the state at all, and the groups decide
		// which nodes.
		if update.Status != nil || update.GroupIDs != nil {
			return bumpNodesForUserGroupsTx(ctx, tx, affected)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return s.UserByID(ctx, id)
}

// DeleteUser removes a user; the cascades take their devices, traffic and
// leases.
func (s *Store) DeleteUser(ctx context.Context, id uint64) error {
	return s.Tx(ctx, func(tx *sqlx.Tx) error {
		groups, err := userGroupIDsTx(ctx, tx, id)
		if err != nil {
			return err
		}
		res, err := tx.ExecContext(ctx, `DELETE FROM users WHERE id = ?`, id)
		if err != nil {
			return fmt.Errorf("store: delete user %d: %w", id, err)
		}
		if affected, _ := res.RowsAffected(); affected == 0 {
			return fmt.Errorf("store: user %d: %w", id, ErrNotFound)
		}
		return bumpNodesForUserGroupsTx(ctx, tx, groups)
	})
}

// ReissueSubToken replaces a user's subscription token, which is how a leaked
// link is revoked. The old link stops working immediately.
func (s *Store) ReissueSubToken(ctx context.Context, id uint64) (string, error) {
	token, err := NewSubToken()
	if err != nil {
		return "", err
	}
	res, err := s.DB.ExecContext(ctx,
		`UPDATE users SET sub_token = ?, sub_token_issued_at = ? WHERE id = ?`,
		token, time.Now().UTC(), id)
	if err != nil {
		return "", fmt.Errorf("store: reissue subscription token for user %d: %w", id, err)
	}
	if affected, _ := res.RowsAffected(); affected == 0 {
		return "", fmt.Errorf("store: user %d: %w", id, ErrNotFound)
	}
	return token, nil
}

// ResetUserTraffic zeroes a user's counter. Only a manual reset exists for
// now; the strategy column is where a scheduled one will read from.
func (s *Store) ResetUserTraffic(ctx context.Context, id uint64) error {
	return s.Tx(ctx, func(tx *sqlx.Tx) error {
		if _, err := tx.ExecContext(ctx,
			`UPDATE users SET traffic_used = 0, last_reset_at = ?,
			 status = CASE WHEN status = ? THEN ? ELSE status END
			 WHERE id = ?`,
			time.Now().UTC(), UserLimited, UserActive, id); err != nil {
			return fmt.Errorf("store: reset user %d traffic: %w", id, err)
		}
		groups, err := userGroupIDsTx(ctx, tx, id)
		if err != nil {
			return err
		}
		// A user who was over their limit is usable again, so the nodes need
		// to hear about it.
		return bumpNodesForUserGroupsTx(ctx, tx, groups)
	})
}

// BulkUserAction is one of the mass operations the admin UI offers.
type BulkUserAction struct {
	UserIDs []uint64
	// ExtendBy adds to the expiry, starting from now for a user who has
	// already expired.
	ExtendBy time.Duration
	// SetStatus, when set, is applied to every user.
	SetStatus string
	// SetGroupIDs, when non-nil, replaces every user's groups.
	SetGroupIDs *[]uint64
	// Delete removes them.
	Delete bool
	// ResetTraffic zeroes their counters.
	ResetTraffic bool
}

// ApplyBulkUserAction runs one mass operation in a single transaction, so a
// failure half way does not leave half the selection changed.
func (s *Store) ApplyBulkUserAction(ctx context.Context, action BulkUserAction) (int, error) {
	if len(action.UserIDs) == 0 {
		return 0, nil
	}
	var affected int
	err := s.Tx(ctx, func(tx *sqlx.Tx) error {
		var groups []uint64
		for _, id := range action.UserIDs {
			userGroups, err := userGroupIDsTx(ctx, tx, id)
			if err != nil {
				return err
			}
			groups = append(groups, userGroups...)
		}

		switch {
		case action.Delete:
			query, args, err := sqlx.In(`DELETE FROM users WHERE id IN (?)`, action.UserIDs)
			if err != nil {
				return fmt.Errorf("store: bulk delete: %w", err)
			}
			res, err := tx.ExecContext(ctx, tx.Rebind(query), args...)
			if err != nil {
				return fmt.Errorf("store: bulk delete: %w", err)
			}
			n, _ := res.RowsAffected()
			affected = int(n)

		case action.ExtendBy > 0:
			// A user who already expired is extended from now, not from a
			// date in the past, which is what an operator means by "extend".
			query, args, err := sqlx.In(
				`UPDATE users SET
					expires_at = DATE_ADD(GREATEST(COALESCE(expires_at, ?), ?), INTERVAL ? SECOND),
					status = CASE WHEN status = ? THEN ? ELSE status END
				 WHERE id IN (?)`,
				time.Now().UTC(), time.Now().UTC(), int64(action.ExtendBy.Seconds()),
				UserExpired, UserActive, action.UserIDs)
			if err != nil {
				return fmt.Errorf("store: bulk extend: %w", err)
			}
			res, err := tx.ExecContext(ctx, tx.Rebind(query), args...)
			if err != nil {
				return fmt.Errorf("store: bulk extend: %w", err)
			}
			n, _ := res.RowsAffected()
			affected = int(n)

		case action.SetStatus != "":
			query, args, err := sqlx.In(`UPDATE users SET status = ? WHERE id IN (?)`,
				action.SetStatus, action.UserIDs)
			if err != nil {
				return fmt.Errorf("store: bulk status: %w", err)
			}
			res, err := tx.ExecContext(ctx, tx.Rebind(query), args...)
			if err != nil {
				return fmt.Errorf("store: bulk status: %w", err)
			}
			n, _ := res.RowsAffected()
			affected = int(n)

		case action.ResetTraffic:
			query, args, err := sqlx.In(
				`UPDATE users SET traffic_used = 0, last_reset_at = ?,
				 status = CASE WHEN status = ? THEN ? ELSE status END
				 WHERE id IN (?)`,
				time.Now().UTC(), UserLimited, UserActive, action.UserIDs)
			if err != nil {
				return fmt.Errorf("store: bulk reset: %w", err)
			}
			res, err := tx.ExecContext(ctx, tx.Rebind(query), args...)
			if err != nil {
				return fmt.Errorf("store: bulk reset: %w", err)
			}
			n, _ := res.RowsAffected()
			affected = int(n)

		case action.SetGroupIDs != nil:
			for _, id := range action.UserIDs {
				if err := setUserGroupsTx(ctx, tx, id, *action.SetGroupIDs); err != nil {
					return err
				}
			}
			affected = len(action.UserIDs)
			groups = append(groups, *action.SetGroupIDs...)

		default:
			return errors.New("store: bulk action has nothing to do")
		}

		return bumpNodesForUserGroupsTx(ctx, tx, groups)
	})
	return affected, err
}

// ---------------------------------------------------------------------------
// Groups
// ---------------------------------------------------------------------------

func setUserGroupsTx(ctx context.Context, tx *sqlx.Tx, userID uint64, groupIDs []uint64) error {
	if _, err := tx.ExecContext(ctx, `DELETE FROM user_group_members WHERE user_id = ?`, userID); err != nil {
		return fmt.Errorf("store: clear user groups: %w", err)
	}
	for _, groupID := range groupIDs {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO user_group_members (user_id, group_id) VALUES (?, ?)`, userID, groupID); err != nil {
			return fmt.Errorf("store: add user %d to group %d: %w", userID, groupID, err)
		}
	}
	return nil
}

func userGroupIDsTx(ctx context.Context, tx *sqlx.Tx, userID uint64) ([]uint64, error) {
	var ids []uint64
	if err := tx.SelectContext(ctx, &ids,
		`SELECT group_id FROM user_group_members WHERE user_id = ?`, userID); err != nil {
		return nil, fmt.Errorf("store: user %d groups: %w", userID, err)
	}
	return ids, nil
}

// UserGroupIDs returns the groups a user may use.
func (s *Store) UserGroupIDs(ctx context.Context, userID uint64) ([]uint64, error) {
	var ids []uint64
	if err := s.DB.SelectContext(ctx, &ids,
		`SELECT group_id FROM user_group_members WHERE user_id = ? ORDER BY group_id`, userID); err != nil {
		return nil, fmt.Errorf("store: user %d groups: %w", userID, err)
	}
	return ids, nil
}

// bumpNodesForUserGroupsTx bumps every node in the given groups, so they pick
// up the change to who they serve.
func bumpNodesForUserGroupsTx(ctx context.Context, tx *sqlx.Tx, groupIDs []uint64) error {
	if len(groupIDs) == 0 {
		return nil
	}
	unique := map[uint64]bool{}
	var ids []uint64
	for _, id := range groupIDs {
		if !unique[id] {
			unique[id] = true
			ids = append(ids, id)
		}
	}
	query, args, err := sqlx.In(
		`UPDATE nodes SET config_version = config_version + 1
		 WHERE id IN (SELECT node_id FROM node_group_members WHERE group_id IN (?))`, ids)
	if err != nil {
		return fmt.Errorf("store: bump nodes for groups: %w", err)
	}
	if _, err := tx.ExecContext(ctx, tx.Rebind(query), args...); err != nil {
		return fmt.Errorf("store: bump nodes for groups: %w", err)
	}
	return nil
}

// UsersForNode returns the users a node must serve: active, within their
// limits, and in a group that includes this node.
//
// This is the query the state renderer uses, so the filtering is here rather
// than in Go: a node must never be handed a user who should not be able to
// connect.
func (s *Store) UsersForNode(ctx context.Context, nodeID uint64) ([]User, error) {
	var out []User
	err := s.DB.SelectContext(ctx, &out,
		`SELECT DISTINCT `+prefixColumns(userColumns, "u")+` FROM users u
		 JOIN user_group_members ugm ON ugm.user_id = u.id
		 JOIN node_group_members ngm ON ngm.group_id = ugm.group_id
		 WHERE ngm.node_id = ?
		   AND u.status = ?
		   AND (u.expires_at IS NULL OR u.expires_at > ?)
		   AND (u.traffic_limit = 0 OR u.traffic_used < u.traffic_limit)
		 ORDER BY u.id`,
		nodeID, UserActive, time.Now().UTC())
	if err != nil {
		return nil, fmt.Errorf("store: users for node %d: %w", nodeID, err)
	}
	return out, nil
}

// NodesForUser returns the online nodes a user may use, for the subscription.
func (s *Store) NodesForUser(ctx context.Context, userID uint64, onlineOnly bool) ([]Node, error) {
	query := `SELECT DISTINCT ` + prefixColumns(nodeColumns, "n") + ` FROM nodes n
		 JOIN node_group_members ngm ON ngm.node_id = n.id
		 JOIN user_group_members ugm ON ugm.group_id = ngm.group_id
		 WHERE ugm.user_id = ? AND n.enabled = 1`
	args := []any{userID}
	if onlineOnly {
		// Only nodes that are actually up go into a subscription: handing a
		// client a dead server is worse than handing it one fewer.
		query += ` AND n.status <> ?`
		args = append(args, NodeOffline)
	}
	query += ` ORDER BY n.name, n.id`

	var out []Node
	if err := s.DB.SelectContext(ctx, &out, query, args...); err != nil {
		return nil, fmt.Errorf("store: nodes for user %d: %w", userID, err)
	}
	return out, nil
}

// ---------------------------------------------------------------------------
// Devices
// ---------------------------------------------------------------------------

// SeenDevice records a device fetching a subscription and enforces the limit.
//
// A device already on the list is just touched. A new one is refused when the
// user is at their limit, which is the whole point of the ledger: the limit is
// on distinct devices, not on concurrent connections, so it is enforced where
// the device identifies itself.
func (s *Store) SeenDevice(ctx context.Context, userID uint64, hwid, model, platform, appVersion, ip string) (*Device, error) {
	if hwid == "" {
		return nil, errors.New("store: no device id given")
	}
	var deviceID uint64
	err := s.Tx(ctx, func(tx *sqlx.Tx) error {
		var existing Device
		err := tx.GetContext(ctx, &existing,
			`SELECT id, user_id, hwid, model, platform, app_version, first_seen_at, last_seen_at, last_ip
			 FROM user_devices WHERE user_id = ? AND hwid = ?`, userID, hwid)
		switch {
		case err == nil:
			deviceID = existing.ID
			if _, err := tx.ExecContext(ctx,
				`UPDATE user_devices SET last_seen_at = ?, last_ip = ?, model = ?, platform = ?, app_version = ?
				 WHERE id = ?`,
				time.Now().UTC(), nullString(ip), nullString(model), nullString(platform),
				nullString(appVersion), existing.ID); err != nil {
				return fmt.Errorf("store: touch device: %w", err)
			}
			return nil

		case errors.Is(err, sql.ErrNoRows):
			// A new device: check the limit under the same transaction, so two
			// phones registering at once cannot both slip past it.
			var limit uint32
			if err := tx.GetContext(ctx, &limit,
				`SELECT devices_limit FROM users WHERE id = ? FOR UPDATE`, userID); err != nil {
				return fmt.Errorf("store: user %d device limit: %w", userID, err)
			}
			if limit > 0 {
				var count uint32
				if err := tx.GetContext(ctx, &count,
					`SELECT COUNT(*) FROM user_devices WHERE user_id = ?`, userID); err != nil {
					return fmt.Errorf("store: count devices: %w", err)
				}
				if count >= limit {
					return ErrDeviceLimit
				}
			}
			res, err := tx.ExecContext(ctx,
				`INSERT INTO user_devices (user_id, hwid, model, platform, app_version, last_ip)
				 VALUES (?, ?, ?, ?, ?, ?)`,
				userID, hwid, nullString(model), nullString(platform), nullString(appVersion), nullString(ip))
			if err != nil {
				return fmt.Errorf("store: add device: %w", err)
			}
			lastID, _ := res.LastInsertId()
			deviceID = uint64(lastID)
			return nil

		default:
			return fmt.Errorf("store: read device: %w", err)
		}
	})
	if err != nil {
		return nil, err
	}

	var device Device
	if err := s.DB.GetContext(ctx, &device,
		`SELECT id, user_id, hwid, model, platform, app_version, first_seen_at, last_seen_at, last_ip
		 FROM user_devices WHERE id = ?`, deviceID); err != nil {
		return nil, fmt.Errorf("store: read device %d: %w", deviceID, err)
	}
	return &device, nil
}

// UserDevices lists a user's devices, most recently seen first.
func (s *Store) UserDevices(ctx context.Context, userID uint64) ([]Device, error) {
	var out []Device
	if err := s.DB.SelectContext(ctx, &out,
		`SELECT id, user_id, hwid, model, platform, app_version, first_seen_at, last_seen_at, last_ip
		 FROM user_devices WHERE user_id = ? ORDER BY last_seen_at DESC`, userID); err != nil {
		return nil, fmt.Errorf("store: user %d devices: %w", userID, err)
	}
	return out, nil
}

// DeleteDevice removes one device, freeing a slot.
func (s *Store) DeleteDevice(ctx context.Context, userID, deviceID uint64) error {
	res, err := s.DB.ExecContext(ctx,
		`DELETE FROM user_devices WHERE id = ? AND user_id = ?`, deviceID, userID)
	if err != nil {
		return fmt.Errorf("store: delete device %d: %w", deviceID, err)
	}
	if affected, _ := res.RowsAffected(); affected == 0 {
		return fmt.Errorf("store: device %d: %w", deviceID, ErrNotFound)
	}
	return nil
}

// MarkSubFetched records that the app fetched a subscription, so the panel can
// show which users are actually using theirs.
func (s *Store) MarkSubFetched(ctx context.Context, userID uint64) error {
	if _, err := s.DB.ExecContext(ctx,
		`UPDATE users SET last_sub_fetch_at = ? WHERE id = ?`, time.Now().UTC(), userID); err != nil {
		return fmt.Errorf("store: mark subscription fetched: %w", err)
	}
	return nil
}

// prefixColumns qualifies a column list with a table alias, so a joined query
// can reuse the same list as a plain one.
func prefixColumns(columns, alias string) string {
	parts := strings.Split(columns, ",")
	for i, part := range parts {
		parts[i] = alias + "." + strings.TrimSpace(part)
	}
	return strings.Join(parts, ", ")
}

func timeOrNull(t *time.Time) any {
	if t == nil {
		return nil
	}
	return t.UTC()
}
